FROM python:3.8-slim

RUN apt-get update && \
	apt-get install -y   gcc musl-dev \
	&& pip install --no-cache-dir RPi.GPIO \
	requests \
	&& apt-get remove -y  gcc musl-dev \
	&& apt-get autoremove -y 

COPY scriptRPI.py ./

CMD ["python", "./scriptRPI.py"]
