FROM python:3.8-slim

RUN apt-get update
RUN apt-get install -y   gcc musl-dev \
	&& pip install --no-cache-dir RPi.GPIO \
	&& apt-get remove -y  gcc musl-dev \
	&& apt-get autoremove -y
RUN pip install --no-cache-dir requests

COPY script.py ./
CMD ["python", "./script.py"]
