FROM python:3.8-slim

RUN apt-get update && \
	apt-get install -y   gcc musl-dev \
	&& pip install --no-cache-dir RPi.GPIO \
	requests \
	&& apt-get remove -y  gcc musl-dev \
	&& apt-get clean && apt-get autoremove -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY scriptRPI.py ./

CMD ["python", "./scriptRPI.py"]
